template: boot_sector
      on: disk.bootsector
  lookup: sum -1s foreach uefi
   units: calls
  plugin: ebpf.plugin
   every: 10s
    warn: $this != 0
   delay: down 10m multiplier 1.5 max 1h
    info: Your boot sector was changed recently.
      to: sysadmin
